plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Applications/XAMPP/xamppfiles/htdocs/My_portfolio"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/index.php"
to = "/index.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/send-mail.php"
to = "/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]