<?php

return [
    'name' => 'Shadab Belim',
    'title' => 'Software Engineer | Full Stack Developer | MCA Graduate',
    'email' => 'Shadabbelim008@gmail.com',
    'phone' => '+91 8827976129',
    'location' => 'Indore, Madhya Pradesh, India',
    'social' => [
        'linkedin' => 'https://www.linkedin.com/in/shadabbelim/',
        'github' => 'https://github.com/Shadabbelim2',
        'fiverr' => 'https://www.fiverr.com/shadabbelim',
    ],
    'about' => 'I am a dedicated MCA graduate with a strong foundation in programming and software engineering. My expertise includes Java, Python, Django, PHP, Laravel, JavaScript, SQL, MongoDB and modern web technologies. I have worked on multiple real-world projects, ranging from responsive websites to machine learning applications.',
    'about_extra' => 'I am passionate about creating user-friendly applications, learning emerging technologies, and contributing to innovative software solutions. My experience in web development and project management has strengthened my problem-solving abilities and teamwork skills.',
    'education' => [
        [
            'degree' => 'Master of Computer Applications (MCA)',
            'institution' => 'Acropolis Institute of Technology and Research, Indore',
            'year' => '2023 – 2025',
            'grade' => '7.9 CGPA',
            'icon' => 'fas fa-graduation-cap',
        ],
        [
            'degree' => 'Bachelor of Science (Mathematics)',
            'institution' => 'Savita Devi Smriti Jaiswal College, Shamgarh',
            'year' => '2019 – 2022',
            'grade' => '8.33 CGPA',
            'icon' => 'fas fa-university',
        ],
    ],
    'experience' => [
        [
            'role' => 'Software Engineer',
            'company' => 'Chapter247 Infotech Pvt. Ltd.',
            'period' => 'Apr 2026 – Present',
            'logo' => 'fas fa-briefcase',
            'gradient' => 'linear-gradient(135deg, #00C9A7, #6C63FF)',
            'gradient2' => 'linear-gradient(135deg, #00C9A7, #6C63FF)',
            'description' => [
                'Develop and maintain enterprise-grade web applications using Laravel, PHP, and MySQL.',
                'Design scalable backend architectures following Clean Architecture, SOLID Principles, and Repository Pattern.',
                'Build secure REST APIs with Role-Based Access Control (RBAC) and authentication systems.',
                'Optimize application performance by improving SQL queries, indexing, caching, and backend logic.',
                'Develop and maintain complex modules including Claim Management, User Management, Permission Management, Reports, and Document Management.',
                'Collaborate with cross-functional teams in Agile/Scrum environments to deliver high-quality software.',
                'Participate in code reviews, debugging, testing, deployment, and production issue resolution.',
                'Work extensively with Git, CI/CD workflows, API integrations, and enterprise software development best practices.',
            ],
            'technologies' => ['Laravel', 'PHP', 'MySQL', 'REST API', 'Git', 'JavaScript', 'HTML', 'CSS', 'Bootstrap', 'Repository Pattern', 'SOLID Principles'],
        ],
        [
            'role' => 'Full Stack Developer (Laravel / PHP Developer)',
            'company' => 'Exaalgia IT Solutions',
            'period' => 'Feb 2025 – Apr 2026',
            'logo' => 'fas fa-laptop-code',
            'gradient' => 'var(--gradient-primary)',
            'gradient2' => 'linear-gradient(135deg, #6C63FF, #00C9A7)',
            'description' => [
                'Developed and maintained scalable web applications using PHP, Laravel, MySQL, JavaScript, HTML, and CSS.',
                'Designed and implemented secure REST APIs for enterprise-level applications.',
                'Worked extensively on backend architecture, authentication, authorization, RBAC, and database optimization.',
                'Improved application performance by optimizing SQL queries and backend logic.',
                'Built reusable services, repositories, and followed SOLID principles and clean architecture.',
                'Integrated third-party APIs and payment gateways where required.',
                'Collaborated with frontend, QA, and product teams in Agile sprints.',
                'Managed Git workflows, pull requests, code reviews, deployments, and bug fixing.',
                'Worked on enterprise claim management modules, user management, permission systems, reporting, and backend optimization.',
            ],
            'technologies' => ['Laravel', 'PHP', 'MySQL', 'REST API', 'JavaScript', 'HTML', 'CSS', 'Bootstrap', 'Git'],
        ],
        [
            'role' => 'Python Backend Developer Intern',
            'company' => 'ABS Soft Tech Pvt. Ltd.',
            'period' => 'May 2024 – Jan 2025',
            'logo' => 'fab fa-python',
            'gradient' => 'linear-gradient(135deg, #FF6B6B, #FFA726)',
            'gradient2' => 'linear-gradient(135deg, #FFA726, #FF6B6B)',
            'description' => [
                'Developed backend applications using Python and Django.',
                'Built REST APIs for AI-based and web applications.',
                'Worked on Artificial Intelligence and Text-to-Speech related modules.',
                'Integrated AI services and automated backend workflows.',
                'Collaborated with frontend developers to build responsive full-stack applications.',
                'Debugged and optimized backend logic for better performance.',
                'Participated in real-world client projects following Agile development practices.',
                'Learned deployment, version control (Git), debugging, and software development lifecycle.',
            ],
            'technologies' => ['Python', 'Django', 'REST API', 'JavaScript', 'HTML', 'CSS', 'Git'],
        ],
    ],
    'skills' => [
        'Programming Languages' => [
            ['name' => 'Python', 'icon' => 'fab fa-python', 'level' => 90],
            ['name' => 'Java', 'icon' => 'fab fa-java', 'level' => 80],
            ['name' => 'JavaScript', 'icon' => 'fab fa-js-square', 'level' => 85],
            ['name' => 'PHP', 'icon' => 'fab fa-php', 'level' => 88],
            ['name' => 'SQL', 'icon' => 'fas fa-database', 'level' => 82],
            ['name' => 'C++', 'icon' => 'fas fa-code', 'level' => 75],
        ],
        'Frontend Development' => [
            ['name' => 'HTML5', 'icon' => 'fab fa-html5', 'level' => 95],
            ['name' => 'CSS3', 'icon' => 'fab fa-css3-alt', 'level' => 90],
            ['name' => 'Bootstrap', 'icon' => 'fab fa-bootstrap', 'level' => 88],
            ['name' => 'JavaScript', 'icon' => 'fab fa-js', 'level' => 85],
        ],
        'Backend Development' => [
            ['name' => 'PHP', 'icon' => 'fab fa-php', 'level' => 88],
            ['name' => 'Laravel', 'icon' => 'fab fa-laravel', 'level' => 85],
            ['name' => 'Django', 'icon' => 'fab fa-python', 'level' => 80],
            ['name' => 'Node.js', 'icon' => 'fab fa-node-js', 'level' => 70],
        ],
        'Database' => [
            ['name' => 'MySQL', 'icon' => 'fas fa-database', 'level' => 85],
            ['name' => 'SQL', 'icon' => 'fas fa-server', 'level' => 82],
        ],
        'Tools & Technologies' => [
            ['name' => 'Git', 'icon' => 'fab fa-git-alt', 'level' => 85],
            ['name' => 'GitHub', 'icon' => 'fab fa-github', 'level' => 88],
            ['name' => 'WordPress', 'icon' => 'fab fa-wordpress', 'level' => 80],
            ['name' => 'VS Code', 'icon' => 'fas fa-laptop-code', 'level' => 90],
            ['name' => 'IntelliJ IDEA', 'icon' => 'fas fa-code', 'level' => 75],
        ],
    ],
    'projects' => [
        [
            'title' => 'My Portfolio Website',
            'description' => 'A fully responsive portfolio website built using HTML, CSS, JavaScript, and PHP.',
            'features' => ['Responsive Design', 'Contact Form Integration', 'Project Showcase', 'Skills & Experience Display', 'Modern UI/UX'],
            'icon' => 'fas fa-globe',
            'color' => '#6C63FF',
        ],
        [
            'title' => 'Smart Canteen System',
            'description' => 'A web-based canteen management system developed using HTML, CSS, JavaScript, PHP, and MySQL.',
            'features' => ['User Authentication', 'Online Food Ordering', 'Order History', 'Receipt Generation', 'OTP Verification', 'Forgot Password Functionality'],
            'icon' => 'fas fa-utensils',
            'color' => '#00C9A7',
        ],
        [
            'title' => 'Saint Umar Academy Website',
            'description' => 'Designed and developed an educational institution website with a focus on usability and user experience.',
            'features' => ['Gallery Section', 'Classroom Information', 'Laboratory Information', 'Responsive Layout', 'Easy Navigation'],
            'icon' => 'fas fa-school',
            'color' => '#FF6B6B',
        ],
        [
            'title' => 'Object Detection Fine-Tuning',
            'description' => 'Machine Learning project focused on improving object detection accuracy using Python.',
            'features' => ['Real-Time Detection', 'Model Fine-Tuning', 'Improved Recognition Accuracy', 'Custom Object Detection'],
            'icon' => 'fas fa-robot',
            'color' => '#FFA726',
        ],
    ],
    'achievements' => [
        [
            'title' => 'Problem Solving',
            'description' => 'Solved 400+ DSA problems on various coding platforms.',
            'icon' => 'fas fa-brain',
        ],
        [
            'title' => 'Sports Achievements',
            'description' => 'Winner of Intercollege Cricket Tournament. District-Level Cricket Tournament Winner.',
            'icon' => 'fas fa-trophy',
        ],
        [
            'title' => 'Leadership & Management',
            'description' => 'Team Leader at PickOne Consulting – Worked in audit operations and management activities.',
            'icon' => 'fas fa-users',
        ],
    ],
    'interests' => [
        ['name' => 'Full Stack Development', 'icon' => 'fas fa-layer-group'],
        ['name' => 'Artificial Intelligence', 'icon' => 'fas fa-brain'],
        ['name' => 'Machine Learning', 'icon' => 'fas fa-robot'],
        ['name' => 'Software Development', 'icon' => 'fas fa-laptop-code'],
        ['name' => 'Cricket', 'icon' => 'fas fa-baseball-ball'],
        ['name' => 'Team Leadership', 'icon' => 'fas fa-users-cog'],
        ['name' => 'Problem Solving', 'icon' => 'fas fa-puzzle-piece'],
    ],
    'stats' => [
        ['value' => '400+', 'label' => 'DSA Problems Solved', 'icon' => 'fas fa-code'],
        ['value' => '4+', 'label' => 'Major Projects', 'icon' => 'fas fa-project-diagram'],
        ['value' => '2+', 'label' => 'Years Coding', 'icon' => 'fas fa-clock'],
        ['value' => '1+', 'label' => 'Year Web Dev', 'icon' => 'fas fa-globe'],
    ],
];
